# Default values for openldap.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

strategy:
  type: Recreate

image:
  repository: firefart/requesttracker
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: nginx-nightly-20230710

imagePullSecrets: []

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# create some initial user data
initialData: []
# - |
#   dn: cn=Barbara Jensen,dc=example,dc=com
#   objectClass: person
#   cn: Barbara Jensen
#   cn: Babs Jensen
#   sn: Jensen
#   title: the world's most famous mythical manager
#   mail: bjensen@example.com
#   uid: bjensen

logLevel: debug

service:
  type: ClusterIP
  http: 80
  https: 443