apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: rt
  name: rtadmin
subjects:
  - kind: ServiceAccount
    name: rt
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io