apiVersion: v1
kind: Secret
metadata:
  name: certs
  labels:
    name: {{ template "request-tracker.name" . }}
    instance: {{ template "request-tracker.name" . }}
    chart: {{ template "request-tracker.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    managed-by: helm
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
type: Opaque
data:
  pub.pem: |
{{ .Files.Get "files/getmail/certs/pub.pem" | b64enc | indent 4 }}