apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nginx.fullname" . }}-certs
  labels:
    name: {{ include "nginx.name" . }}
    instance: {{ include "nginx.name" . }}
    chart: {{ include "nginx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    managed-by: helm
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
type: Opaque
data:
  priv.pem: |
{{ .Files.Get "files/nginx/certs/priv.pem" | b64enc | indent 4 }}
  pub.pem: |
{{ .Files.Get "files/nginx/certs/pub.pem" | b64enc | indent 4 }}