apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nginx.fullname" . }}-conf
  labels:
    name: {{ include "nginx.name" . }}
    instance: {{ include "nginx.name" . }}
    chart: {{ include "nginx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    managed-by: helm
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
type: Opaque
data:
{{ (.Files.Glob "files/nginx/conf/*").AsSecrets | indent 2 }}